#define h_Obsah                                  0
#define h_OProgramu                             10
#define h_InstalaceProgramu                     20
#define h_16BitovaA32Bitova                     30
#define h_RychlyUvodDo                          50
#define h_PodrobnyPopisProgramu                 60
#define h_MDIProstrediProgramu                  70
#define h_NabidkyListaS                         80
#define h_ZalozeniDatabaze                      90
#define h_PrecteniObsahuDisku                  100
#define h_JmenoDisku                           110
#define h_AktualizaceDisku                     115
#define h_SejmutiSlozky                        116
#define h_ZjistovaniObsahuKomprimovanych       120
#define h_OknoSDatabazi                        130
#define h_AktualniAVybrane                     140
#define h_PanelSDisky                          150
#define h_PanelSeStromem                       160
#define h_PanelSeSoubory                       170
#define h_StavovyRadek                         172
#define h_Popisky                              180
#define h_ManualniTvorbaPopisek                190
#define h_AutomatickaTvorbaPopisek             200
#define h_VyhledavaniVDatabazi                 210
#define h_Maska                                220
#define h_VyhledavaniSouboru                   230
#define h_VyhledavaniVybranychSouboru          240
#define h_OknoSVyhledanymi                     250
#define h_VypsaniVolnychMist                   260
#define h_OknoSVypisem                         270
#define h_InformaceODisku                      280
#define h_NastaveniProgramu                    290
#define h_NastaveniDatabaze                    300
#define h_KopirovaniDoSchranky                 310
#define h_Tisk                                 320
#define h_KompreseDatabaze                     330
#define h_ExportDatabaze                       340
#define h_VyvoreniDatabazeJen                  350
#define h_ImportDatabaze                       360
#define h_AutomatickyRezim                     370
#define h_TechnickeUdajeO                      380
#define h_CoDelatV                             390
#define h_FAQOdpovediNa                        400
#define h_RegistracniProcedura                 410
#define h_SeznamTypuArchivnich                 420
#define h_TvorbaKonverznichFiltru              430
#define h_InstallationComplete                1000
